name: Windows Build (MSVC)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: "3.13"

      - name: Install Meson + Ninja
        run: pip install meson ninja

      - name: Set up MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure project with Meson
        working-directory: bindings/c
        run: meson setup builddir

      - name: Compile with Ninja
        working-directory: bindings/c
        run: ninja -C builddir

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pine-c-dll-windows
          path: builddir/libpine_c.dll
